### ISSUE TITLE
Add support for getting the report format from .coveragerc

### ISSUE THREAD

**Issue by rfleschenberg** [ionelmc/pytest-cover#1]
It would be nice if I could keep all my coverage-related settings in one place. Right now, I have this:

pytest.ini:

```
[pytest]
addopts=--cov-report term-missing
```

.coveragerc:

```
[run]
show_missing = True
# more settings...
```

I am not sure how to implement this in a clean way, but it would be wonderful if pytest-cov / pytest-cover respected all the .coveragerc settings.

**Comment by ionelmc** [comment]
It appears `--cov-report` supports multiple reports, eg: you can do something like `--cov-report=term --cov-report=xml`.

I think it would be fine if you have `--cov-report=term` and `show_missing = True` would switch the report to `term-missing`, agree?

**Comment by ionelmc** [comment]
Ok so I've made some changes: `--cov-report=term` will add the missing lines if you have `show_missing=true` in your `.coveragerc`.

Try the changes with `pip install https://github.com/ionelmc/pytest-cover/archive/master.zip`

**Comment by rfleschenberg** [comment]
Works fine here. Thanks!
