### ISSUE TITLE
Add support for --fail-unser

### ISSUE THREAD

**Issue by rfleschenberg** [ionelmc/pytest-cover#2]
coverage 4+ supports setting a `fail_under` option from .coveragerc. It would be great to have that in pytest-cover.

**Comment by ionelmc** [comment]
There's a `--cov-min` option. Does that work for you? (ignoring the fact that it's not read from `.coveragerc`)

**Comment by rfleschenberg** [comment]
Yep, that works. Thank you. If it was read from .coveragerc, it would be perfect ;)

**Comment by ionelmc** [comment]
I think I'm going to rename `--cov-min` to `--cov-fail-under` - to have some consistency.
